### ISSUE TITLE
Есть ли вероятность блокировки тг аккаунта?

### ISSUE THREAD

**Issue by Nord1cWarr1or** [Alexell/MuskEmpireBot#10]
Есть ли вероятность блокировки ТГ аккаунта при использовании _нескольких_ ботов на одном аккаунте? например этот бот + memfi + hamster и т.д. 
Насколько я понимаю, здесь запросы идут через tg API, и какова верояность того, что тг посчитает запросы слишком частыми или что-то в этом роде?

**Comment by avtosubaru25** [comment]
не не ссы не посчитает только если ты не будешь бомбить тг с частотой меньше 0,1 сек

> Есть ли вероятность блокировки ТГ аккаунта при использовании _нескольких_ ботов на одном аккаунте? например этот бот + memfi + hamster и т.д. Насколько я понимаю, здесь запросы идут через tg API, и какова верояность того, что тг посчитает запросы слишком частыми или что-то в этом роде?

**Comment by Alexell** [comment]
Поддерживаю. Сам держу 8 ботов на своем аккаунте и все нормально.

**Comment by Nord1cWarr1or** [comment]
окей, спасибо
