### ISSUE TITLE
Не работает бот

### ISSUE THREAD

**Issue by Newmcpe** [Alexell/MuskEmpireBot#13]
![image](https://github.com/user-attachments/assets/bf04e792-6492-4203-9409-fe526d7399e2)

Использую последнюю версию бота

**Comment by asafov** [comment]
Обсуждения посмотри, там всё написано)

**Comment by Newmcpe** [comment]
хотя у меня в принципе с этого аккаунта даже в приложении телеграм не заходит

**Comment by asafov** [comment]
Так ты же вроде бан получила на своем же боте) С чего другие боты будут работать?)

**Comment by Newmcpe** [comment]
> Так ты же вроде бан получила на своем же боте) С чего другие боты будут работать?)

Может повезло бы :D Ладно, пойду фиксить своего бота и тестить на новом аккаунте

**Comment by Alexell** [comment]
#9
