### ISSUE TITLE
Сумма вклада в инвестировании

### ISSUE THREAD

**Issue by Alexell** [Alexell/MuskEmpireBot#16]
Хочу сделать автоматический рассчет суммы инвестирования, т.к. она меняется с ростом уровня и дохода в час и постоянно обновлять её в `.env` не удобно.
У кого есть возможность, можете написать в коментах краткую сводку по вашему акку? Вот в таком виде:
```
- Уровень: 3
- Доход в час: 26900
- Суммы инвестирования: 5K, 10K, 15K, 20K, 25K, 30K, 35K
```

```
- Уровень: 7
- Доход в час: 388100
- Суммы инвестирования: 60K, 120K, 180K, 240K, 300K, 360K, 420K
```

Суммы инвестирования - это **все суммы**, которые предлагает вам слайдер, от меньшей слева к большей справа. Мне очень важно получить несколько подобных сводок со всеми суммами инвестирования.

**Comment by asafov** [comment]
Уровень - 15
Доход в час - 74 040 650
Суммы сделаю через 4 часа, когда на main аккаунте станет доступно инвестирование.

**Comment by testingstrategy** [comment]
Вот формула расчета мин и макс ставки, если хочешь поиграться с промежуточными ставками, то множь мин ставку от 1(мин) до 7(макс)

```python
def roundthemnumbers(value):
    x = math.floor(value)
    if (value - x) < .5:
        return x
    else:
        return math.ceil(value)

def t(s, c=100):
    return roundthemnumbers(s / c) * c

def smartZeroRound(e):
    if e < 100:
        e = t(e, 50)
    elif e < 1e3:
        e = t(e, 100)
    elif e < 1e4:
        e = t(e, 1e3)
    elif e < 1e5:
        e = t(e, 1e4)
    elif e < 1e6:
        e = t(e, 1e5)
    elif e < 1e7:
        e = t(e, 1e6)
    elif e < 1e8:
        e = t(e, 1e7)
    else:
        e = t(e, 1e3)
    return e

def Bet(heroLvl, moneyPerHour):
    betStepsCount = 7
    e = 2
    if heroLvl < 3:
        e = 5
    elif heroLvl < 6:
        e = 4
    elif heroLvl < 10:
        e = 3
    o = smartZeroRound(
        (moneyPerHour * e) / (betStepsCount * 3)
    )
    min_bet = o or 100
    max_bet = min_bet * betStepsCount
    return min_bet, max_bet
```

**Comment by Alexell** [comment]
Спасибо, но это я уже сделал.
![изображение](https://github.com/user-attachments/assets/5c0495c2-5ff8-4cd4-87a6-d771d720f091)

**Comment by ButCheR-PRO** [comment]
```
- Уровень: 20
- Доход в час: 1 200 810 800
- Суммы инвестирования: 114.3M, 228.7M, 343M, 457.4M, 571.8M, 686.1M, 800.5M
```

**Comment by Alexell** [comment]
Спасибо, уже не актуально.
