### ISSUE TITLE
Can you make auto buy on Shop?

### ISSUE THREAD

**Issue by ngocbae98** [Alexell/MuskEmpireBot#5]
Can you make auto buy on Shop function for increase profit per hours?.
Thanks for your bot <3

**Comment by BigNeam** [comment]
async def run(self, proxy: str | None) -> None:
    proxy_conn = ProxyConnector().from_url(proxy) if proxy else None

    async with aiohttp.ClientSession(headers=headers, connector=proxy_conn) as http_client:
        self.http_client = http_client
        if proxy:
            await self.check_proxy(proxy=proxy)

        self.authorized = False
        while True:
            if self.errors >= config.ERRORS_BEFORE_STOP:
                log.error(f"{self.session_name} | Bot stopped (too many errors)")
                break
            try:
                if not self.authorized:
                    login_data = await self.get_tg_web_data(proxy=proxy)
                    if await self.login(json_data=login_data):
                        log.success(f"{self.session_name} | Login successful")
                        self.authorized = True
                        self.http_client.headers['Api-Key'] = self.api_key
                        self.dbs = await self.get_dbs()
                        full_profile = await self.get_profile(full=True)
                        if self.user_id is None: self.user_id = int(full_profile['data']['profile']['id'])
                        self.balance = int(full_profile['data']['hero']['money'])
                        offline_bonus = int(full_profile['data']['hero']['offlineBonus'])
                        if offline_bonus > 0:
                            if await self.get_offline_bonus():
                                log.success(f"{self.session_name} | Offline bonus claimed: +{offline_bonus}")
                        else:
                            log.info(f"{self.session_name} | Offline bonus not available")
                    else:
                        continue

                profile = await self.get_profile(full=False)
                self.balance = int(profile['data']['hero']['money'])
                log.info(f"{self.session_name} | Level: {profile['data']['hero']['level']} | "
                                f"Balance: {self.balance} | "
                                f"Money per hour: {profile['data']['hero']['moneyPerHour']}")

                daily_rewards = full_profile['data']['dailyRewards']
                daily_index = None
                for day, status in daily_rewards.items():
                    if status == 'canTake':
                        daily_index = day
                        break
                if daily_index is not None:
                    log.info(f"{self.session_name} | Daily reward available")
                    daily_claimed = await self.daily_reward(index=daily_index)
                    if daily_claimed:
                        log.success(f"{self.session_name} | Daily reward claimed")
                        self.errors = 0
                else:
                    log.info(f"{self.session_name} | Daily reward not available")

                unrewarded_quests = [quest['key'] for quest in full_profile['data']['quests'] if not quest['isRewarded']]
                if unrewarded_quests:
                    log.info(f"{self.session_name} | Quest rewards available")
                    for quest in unrewarded_quests:
                        if await self.quest_reward(quest=quest):
                            log.success(f"{self.session_name} | Reward for quest {quest} claimed")

                await self.daily_quests()

                unrewarded_friends = [int(friend['id']) for friend in full_profile['data']['friends'] if friend['bonusToTake'] > 0]
                if unrewarded_friends:
                    log.info(f"{self.session_name} | Reward for friends available")
                    for friend in unrewarded_friends:
                        if await self.friend_reward(friend=friend):
                            log.success(f"{self.session_name} | Reward for friend {friend} claimed")

                if config.TAPS_ENABLED:
                    per_tap = profile['data']['hero']['earns']['task']['moneyPerTap']
                    max_energy = profile['data']['hero']['earns']['task']['limit']
                    energy = profile['data']['hero']['earns']['task']['energy']
                    if energy == max_energy:
                        await self.perform_taps(per_tap=per_tap, energy=energy)

                if config.PVP_ENABLED:
                    if self.dbs:
                        league_data = None
                        for league in self.dbs['dbNegotiationsLeague']:
                            if league['key'] == config.PVP_LEAGUE:
                                league_data = league
                                break;

                        if league_data is not None:
                            if int(profile['data']['hero']['level']) >= int(league_data['requiredLevel']):
                                self.strategies = [strategy['key'] for strategy in self.dbs['dbNegotiationsStrategy']]
                                if config.PVP_STRATEGY == 'random' or config.PVP_STRATEGY in self.strategies:
                                    await self.perform_pvp(league=league_data, strategy=config.PVP_STRATEGY, count=config.PVP_COUNT)
                                else:
                                    config.PVP_ENABLED = False
                                    log.warning(f"{self.session_name} | PVP_STRATEGY param is invalid. PvP negotiations disabled.")
                            else:
                                config.PVP_ENABLED = False
                                log.warning(f"{self.session_name} | Your level is too low for the {config.PVP_LEAGUE} league. PvP negotiations disabled.")
                        else:
                            config.PVP_ENABLED = False
                            log.warning(f"{self.session_name} | PVP_LEAGUE param is invalid. PvP negotiations disabled.")
                    else:
                        log.warning(f"{self.session_name} | Database is missing. PvP negotiations will be skipped this time.")

                # Автопрокачка карточек
                cards_to_upgrade = [card['id'] for card in full_profile['data']['cards'] if not card['isMaxLevel']]
                if cards_to_upgrade:
                    log.info(f"{self.session_name} | Card upgrades available")
                    for card_id in cards_to_upgrade:
                        if await self.upgrade_card(card_id=card_id):
                            log.success(f"{self.session_name} | Card {card_id} upgraded")

                profile = await self.get_profile(full=False)
                self.balance = int(profile['data']['hero']['money'])
                log.info(f"{self.session_name} | Level: {profile['data']['hero']['level']} | "
                                f"Balance: {self.balance} | "
                                f"Money per hour: {profile['data']['hero']['moneyPerHour']}")

                log.info(f"{self.session_name} | Sleep 1 hour")
                await asyncio.sleep(3600)
                self.authorized = False

            except RuntimeError as error:
                raise error
            except Exception as error:
                log.error(f"{self.session_name} | Unknown error: {error}")
                await asyncio.sleep(delay=3)
Можно так получится

**Comment by Alexell** [comment]
@ngocbae98 This will be done soon.

**Comment by Alexell** [comment]
Further discussion of this issue will be in #2
