### ISSUE TITLE
Error: 401

### ISSUE THREAD

**Issue by skanhell** [Alexell/MuskEmpireBot#9]
2024-07-27 15:58:24 | SUCCESS  | 397 | Test| Login successful
2024-07-27 15:58:25 | ERROR    | 107 | Test| Database error: 401, message='Unauthorized', url=URL('https://api.muskempire.io/dbs')
2024-07-27 15:58:28 | ERROR    | 121 | Test| Profile data error: 401, message='Unauthorized', url=URL('https://api.muskempire.io/user/data/all')
2024-07-27 15:58:31 | ERROR    | 511 | Test| Unknown error: 'data'
2024-07-27 15:58:34 | ERROR    | 121 | Test | Profile data error: 401, message='Unauthorized', url=URL('https://api.muskempire.io/hero/balance/sync')
2024-07-27 15:58:37 | ERROR    | 511 | Test| Unknown error: 'data'
2024-07-27 15:58:40 | ERROR    | 391 | Test| Bot stopped (too many errors)

**Comment by shelllshock** [comment]
Same problem.

**Comment by khosrowkhazraei** [comment]
Same here as well

**Comment by iLimus** [comment]
То же самое...
Со смартфона заходит норм.

**Comment by Alexell** [comment]
Musk Empire implemented a signature of all requests with a special hash, so for now the bot is dead. I will try to solve this problem if I can.

**Comment by ngocbae98** [comment]
Bot stoped, to many error

**Comment by avtosubaru25** [comment]
> Musk Empire implemented a signature of all requests with a special hash, so for now the bot is dead. I will try to solve this problem if I can.

да пиздюки 
			# "chatId":"",
			# "chatType":"sender",
			# "chatInstance":"8801988294589563843"}  последний можно на шару рандомайсом делать а вот чат ид непойму откуда он берет ты не нашол
 еще ?

chat_instance =await self.generate_random_chat_instance()

	async def generate_random_chat_instance(self, length=16):
		characters = '0123456789'
		return ''.join(random.choice(characters) for _ in range(length))

**Comment by Alexell** [comment]
@avtosubaru25 ты не в ту сторону вообще смотришь. Процесс авторизации у них не поменялся, он работает в моем боте и там не нужны chatId и chatInstance. Проблема не в авторизации, а в том, что они добавили заголовки Api-Hash и Api-Time к КАЖДОМУ запросу. Api-Hash генерируется каждый раз по их кастомному алгоритму, который мне не удалось пока воссоздать на Python.

**Comment by seriowag** [comment]
а у тебя есть значения этих Api-Hash. попробовать спросит ChatGPT,может он какой алгоритм по генерации этих хаш узнает?

**Comment by Alexell** [comment]
У нас есть алгоритм хеширования, он прописан у них в js и с ChatGPT я уже вчера поработал на эту тему. Алгоритм похож на md5, но отличается. Если бы это оказался обычный известный алгоритм, у меня не возникло бы проблем. В MMPro BUMP тоже сделали подпись запросов, но там было не сложно воссоздать такую же подпись и мой бот работает. Но тут даже ChatGPT не смог нормально воссоздать алгоритм на Python.

**Comment by seriowag** [comment]
а нет для Python библиотек которые запускают Javascript код?

**Comment by avtosubaru25** [comment]
да да я понял тоже вчера сидел парсил их код они хешат время и апи кей
перепробавал штук 20 алгоритмов неполучилось , пробовал их перенести на
пайтон но я далек от джавы а ГПТ скотина еще тупенький для этого

сб, 27 июл. 2024 г. в 23:51, Alexander ***@***.***>:

**Comment by seriowag** [comment]
а что если так в питоне 
```
def Fx(time, request_auth_payload):
command = ['node', 'md5.js', str(time/ 1000), json.dumps(request_auth_payload)]
result = subprocess.run(command, capture_output=True, text=True)
return result.stdout
```
а в md5.js файле 
```
function Dx(e) {-----}
function Fx(time, payLoad) {
    return Dx(`${time}_${payLoad}`)
}

function main(time, paylod) {
    const jsonString = JSON.stringify(paylod)
    console.log(Fx(time, jsonString ? jsonString : ""));
}

// Get input from command line arguments
const argvTime = parseInt(process.argv[2]);
const argvPayload = JSON.parse(process.argv[3]);

main(argvTime, argvPayload);
```

**Comment by avtosubaru25** [comment]
Так ты тестовых оригинал ключа возьми да сравни что бы у тебя третий
получилься , понял про что ? Если нет стукни в тг @alligatorCCCP

вс, 28 июл. 2024 г., 21:52 sergio ***@***.***>:

**Comment by efsfssf** [comment]
Same problem

**Comment by Alexell** [comment]
**Актуальная информация:** сперва я действительно запускал хеширование через выдранные из их js функции с помощью execjs + Node.js и даже смог в одну секунду обновить страницу и сделать запрос в боте и сравнить хеш, хеш правильный. Потом, выяснилось, что их хеш, это все таки обычный md5. Но проблема в том, что даже с Api-Time и правильным Api-Hash, я все равно получаю 401.

**Comment by Alexell** [comment]
Создал отдельную ветку `hast-test`, прописал генерацию хеша и установку заголовков в первые функции, которые выполняются ботом по порядку. Все равно он получает 401 и в get_dbs и в get_profile, если удастся это исправить, потом в остальные можно будет прописать. Посмотрите, может я что-то упустил.

**Comment by avtosubaru25** [comment]
извиняюсь за флуд вот прочто я говорил берем оригенальные АПИ кей время и
апи хеш из дев ХРОМА, прогоняем через прогу и смотрим получилось генерить
АПИ ХЕШ



import hashlib
import hmac

# Оригинальные методы
def generate_md5_hash(api_key, api_time):
    raw_string = f"{api_key}:{api_time}"
    print(f"MD5 raw string: {raw_string}")
    return hashlib.md5(raw_string.encode()).hexdigest()

def generate_sha256_hash(api_key, api_time):
    raw_string = f"{api_key}:{api_time}"
    print(f"SHA-256 raw string: {raw_string}")
    return hashlib.sha256(raw_string.encode()).hexdigest()

def generate_sha1_hash(api_key, api_time):
    raw_string = f"{api_key}:{api_time}"
    print(f"SHA-1 raw string: {raw_string}")
    return hashlib.sha1(raw_string.encode()).hexdigest()

def generate_hmac_sha256_hash(api_key, api_time):
    raw_string = f"{api_key}:{api_time}"
    print(f"HMAC-SHA256 raw string: {raw_string}")
    return hmac.new(api_key.encode(), raw_string.encode(),
hashlib.sha256).hexdigest()

def generate_hmac_md5_hash(api_key, api_time):
    raw_string = f"{api_key}:{api_time}"
    print(f"HMAC-MD5 raw string: {raw_string}")
    return hmac.new(api_key.encode(), raw_string.encode(),
hashlib.md5).hexdigest()

def generate_custom_order_sha256_hash(api_key, api_time):
    raw_string = f"{api_time}:{api_key}"
    print(f"Custom Order SHA-256 raw string: {raw_string}")
    return hashlib.sha256(raw_string.encode()).hexdigest()

def generate_custom_order_md5_hash(api_key, api_time):
    raw_string = f"{api_time}:{api_key}"
    print(f"Custom Order MD5 raw string: {raw_string}")
    return hashlib.md5(raw_string.encode()).hexdigest()

# Новые методы
def generate_custom_md5_variant(api_key, api_time):
    raw_string = f"{api_key}:{api_time}:secret"
    print(f"Custom MD5 Variant raw string: {raw_string}")
    return hashlib.md5(raw_string.encode()).hexdigest()

def generate_custom_sha256_variant(api_key, api_time):
    raw_string = f"{api_key}:{api_time}:secret"
    print(f"Custom SHA-256 Variant raw string: {raw_string}")
    return hashlib.sha256(raw_string.encode()).hexdigest()

def generate_hmac_sha256_variant(api_key, api_time):
    raw_string = f"{api_key}:{api_time}"
    print(f"HMAC-SHA256 Variant raw string: {raw_string}")
    return hmac.new("secret_key".encode(), raw_string.encode(),
hashlib.sha256).hexdigest()

# Функция сравнения
def compare_hashes(api_key, api_time, original_hash):
    methods = {
        "MD5": generate_md5_hash,
        "SHA-256": generate_sha256_hash,
        "SHA-1": generate_sha1_hash,
        "HMAC-SHA256": generate_hmac_sha256_hash,
        "HMAC-MD5": generate_hmac_md5_hash,
        "Custom Order SHA-256": generate_custom_order_sha256_hash,
        "Custom Order MD5": generate_custom_order_md5_hash,
        "Custom MD5 Variant": generate_custom_md5_variant,
        "Custom SHA-256 Variant": generate_custom_sha256_variant,
        "HMAC-SHA256 Variant": generate_hmac_sha256_variant,
    }

    for name, method in methods.items():
        generated_hash = method(api_key, api_time)
        if generated_hash == original_hash:
            print(f"Method '{name}' generated the correct hash:
{generated_hash}")
        else:
            print(f"Method '{name}' generated a different hash:
{generated_hash}")

if __name__ == "__main__":
    api_key =
"01ab5671ba1c7a8fac3d379e770df491f2f70750884bf412ec5e6e244ed4c39e"
    api_time = "1722119719"
    original_hash = "fb2deda64b34b594a7a5a7edef1466b2"

    compare_hashes(api_key, api_time, original_hash)

пн, 29 июл. 2024 г. в 00:11, Alexander ***@***.***>:

**Comment by avtosubaru25** [comment]
но у меня не вышло ибо не шарю в джаве
может он еще что то мешает кроме этих ключей хотя хеш похож на мд5

пн, 29 июл. 2024 г. в 00:56, Дмитрий Шульц ***@***.***>:

**Comment by seriowag** [comment]
похоже это чтото другое. у меня локально логин проходит без хэш и тайм. 
```
я сточку убрал в логин методе
# await self.set_hash_headers(data=json_data)
```
и в консоле

```
2024-07-29 10:13:30 | SUCCESS  | 427 | sw-musk-1 | Login successful
2024-07-29 10:13:31 | ERROR    | 120 | sw-musk-1 | Database error: 401, message='Unauthorized', url=URL('https://api.muskempire.io/dbs')
```

**Comment by iLimus** [comment]
Я не специалист по WEB... Может чушь напишу, но...
Может это время в каждом заголовке должно быть больше предыдущего?
Поэтому и не прошел запрос в боте, аналогичный тому, что был в дебагере....

**Comment by avtosubaru25** [comment]
ну там даже первый пост запрос не проходит ТРУ поэтому далее это уже не
важно пока , а так то возможно дальше не проходил например

пн, 29 июл. 2024 г. в 03:56, iLimus ***@***.***>:

**Comment by iLimus** [comment]
Т.е. это самый первый запрос от приложения на сервер и он не проходит?
До него приложение совсем ничего не получает?

**Comment by seriowag** [comment]
может они что-то в куки прописывают. я в боте не видел чтобы они считывались и просаживались

**Comment by Alexell** [comment]
@seriowag логин действительно проходит, в нем похоже забыли или не стали делать проверки, все равно дальше него не пройти.
@iLimus это и так понятно, что время и рассчет хеша с учетом времени, при каждом запросе разный, берется текущий unixtime.
@seriowag нет, я не видел у них кук вообще, там только куки то ли Google Analytics, то ли CloudFlare, не помню уже.

**Актуальная информация:** по хешу вопрос закрыт, с ним все хорошо. Но ошибка авторизации сохранилась. Мне тут один человечек помогал тестить и у нас появилась теория. Возможно скоро все починим.

**Comment by BigNeam** [comment]
> @seriowagрегистрация действительно проходит, в нем видно забыли или не стали делать проверки, все равно дальше его не пройти. @iLimusэто и так понятно, что время и рассчет хеша с учетом времени, при каждом запросе разный, берется текущий unixtime. @seriowagнет, я не видел у них кук вообще, там только куки то ли Google Analytics, то ли CloudFlare, не помню уже.
> 
> **Актуальная информация:** по хешу вопрос закрыт, с ним все хорошо. Ошибка авторизации сохранилась. Мне тут один человечек вызвал тестить и у нас появилась теория о том, что проблема вообще не в хеше. Возможно скоро все починим.

Буду ждать от Вас хороших новостей. 
Спасибо за ваш труд.

**Comment by seriowag** [comment]
Похоже да, хеш и время используется только для валидации реквест пейлода. а так как веб асинхронно делают и реквесты параллельно идут, время может быть одинаковое
Ждем апдейта

**Comment by Duwaz** [comment]
В боте в /dbs не вижу параметра lang, в запросе.
Ожидается: `{dbs: e, lang: this.stores.user.settings.lang}`
*бота не чинит

**Comment by asafov** [comment]
Подтверждаю, что метод выше работает. Нужно теперь только везде навтыкать
`await self.set_hash_headers(data=json_data)` где требуется. Где массив не объявлен - там {} видимо.

**Comment by seriowag** [comment]
и в методе get_offline_bonus перед post call надо await self.set_hash_headers(data={}) добавить

**Comment by Alexell** [comment]
А я был так близко к решению... Аж смешно, что дело было в `json.dumps`. В ближайшее время всё проверю, допишу set_hash_headers и выкачу обнову.

**Comment by asafov** [comment]
> А я был так близок к решению... Аж смешно, что дело было в `json.dumps`. В ближайшее время всё проверю, допишу set_hash_headers и выкачу обнову.

Главное - итоговый результат) Для этого и нужно комьюнити)
